### PR TITLE
Monitoring in chaos

### PR DESCRIPTION
**Pull request by Gbahdeyboh**
Signed-off-by: Gbahdeyboh gbahdeybohbello@gmail.com

This is the tutorial for Observing Chaos Impact On Services.

Google Docs => https://docs.google.com/document/d/1faVxpc_yLEBjR_7xhj6xu8zVt7HqK3tr18j9WQ88MuY/edit?usp=sharing

Codelabs => https://codelabs-preview.appspot.com/?file_id=1faVxpc_yLEBjR_7xhj6xu8zVt7HqK3tr18j9WQ88MuY#0

### CODE REVIEW

**Comment by uditgaurav** [comment]
Thanks @Gbahdeyboh ! Some comments on the docs, also pls check if we can remove [.vscode](https://github.com/litmuschaos/tutorials/tree/master/.vscode).

**Review by ishangupta-ds — CHANGES_REQUESTED** [review]
The chaos injection events are missing, please add the same.

**Comment by Gbahdeyboh** [comment]
@uditgaurav I have made the suggested changes

**Comment by Gbahdeyboh** [comment]
@ishangupta-ds I don't understand. Can you share more context?

**Comment by Gbahdeyboh** [comment]
@ishangupta-ds I don't understand. Can you share more context?

**Comment by ishangupta-ds** [comment]
https://docs.litmuschaos.io/docs/2.0.0/user-guides/view-chaos-impact#dashboard-navigation

https://docs.litmuschaos.io/docs/2.0.0/integrations/grafana#interleaved-chaos-result-verdicts

**Comment by Gbahdeyboh** [comment]
I made changes @ishangupta-ds. What do you think?

**Review by ishangupta-ds — APPROVED** [review]

**Review by uditgaurav — APPROVED** [review]

**Pull request merged**
